version: "3.8"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - CLIENT_ORIGIN=http://localhost:3000
    depends_on:
      - redis

volumes:
  redisdata:
